import { ModelProviders, CustomProviderConfig } from '@/types';
import OneDocsIcon from '../../app-icon.png';

const ONEDOCS_BASE_URL = import.meta.env.VITE_ONEDOCS_API_URL || '';
const ONEDOCS_API_KEY = import.meta.env.VITE_ONEDOCS_API_KEY || '';

export const createCustomProvider = (
  name: string,
  baseUrl: string,
  model: string
): CustomProviderConfig => ({
  id: `custom_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
  name,
  baseUrl,
  model,
  isCustom: true,
});

export const MODEL_PROVIDERS: ModelProviders = {
  onedocs: {
    name: 'OneDocs',
    baseUrl: ONEDOCS_BASE_URL,
    endpoint: '/chat/completions',
    models: [
      { value: 'Qwen/Qwen2.5-7B-Instruct', name: 'Qwen2.5-7B Instruct' },
      { value: 'Qwen/Qwen3-8B', name: 'Qwen3-8B' },
      { value: 'THUDM/glm-4-9b-chat', name: 'GLM-4-9B Chat' },
      { value: 'THUDM/GLM-Z1-9B-0414', name: 'GLM-Z1-9B 0414' },
      { value: 'THUDM/GLM-4.1V-9B-Thinking', name: 'GLM-4.1V-9B Thinking' },
      { value: 'THUDM/GLM-4-9B-0414', name: 'GLM-4-9B 0414' },
      { value: 'deepseek-ai/DeepSeek-R1-0528-Qwen3-8B', name: 'DeepSeek-R1 Qwen3-8B' },
      { value: 'glm-4-flash', name: 'GLM-4-Flash' },
    ],
    defaultModel: 'glm-4-flash',
    keyLabel: 'OneDocs API Key',
    keyHint: 'OneDocs 内置凭证，无需额外填写',
    baseUrlHint: 'OneDocs 内置服务地址',
    icon: OneDocsIcon,
    badgeText: '免费模型',
    badgeVariant: 'success',
    requiresApiKey: false,
    requiresBaseUrl: false,
    showApiKeyField: false,
    showBaseUrlField: false,
    credentialsReadOnly: true,
    allowModelCustomization: false,
    defaultApiKey: ONEDOCS_API_KEY,
    description:
      'OneDocs为用户提供免费模型，开箱即用，额度原因有概率无法使用，若无法使用请替换其他模型，感谢配合！',
  },
  openai: {
    name: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    endpoint: '/chat/completions',
    models: [
      { value: 'gpt-4o', name: 'GPT-4o' },
      { value: 'gpt-4o-mini', name: 'GPT-4o-mini' },
      { value: 'gpt-4', name: 'GPT-4' },
      { value: 'gpt-3.5-turbo', name: 'GPT-3.5 Turbo' },
    ],
    defaultModel: 'gpt-4o',
    keyLabel: 'OpenAI API Key',
    keyHint: '需要填入有效的OpenAI API密钥方可使用',
    baseUrlHint: 'API服务器地址，默认为OpenAI官方地址',
    icon: 'https://unpkg.com/@lobehub/icons-static-png@latest/light/openai.png',
  },
  anthropic: {
    name: 'Anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
    endpoint: '/messages',
    models: [
      { value: 'claude-3-5-sonnet-20241022', name: 'Claude 3.5 Sonnet (New)' },
      { value: 'claude-3-5-haiku-20241022', name: 'Claude 3.5 Haiku' },
      { value: 'claude-3-opus-20240229', name: 'Claude 3 Opus' },
      { value: 'claude-3-sonnet-20240229', name: 'Claude 3 Sonnet' },
    ],
    defaultModel: 'claude-3-5-sonnet-20241022',
    keyLabel: 'Anthropic API Key',
    keyHint: '请输入 Anthropic API Key',
    baseUrlHint: 'API服务器地址',
    icon: 'https://unpkg.com/@lobehub/icons-static-png@latest/light/anthropic.png',
  },
  gemini: {
    name: 'Google Gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    endpoint: '/chat/completions',
    models: [
      { value: 'gemini-3-pro', name: 'Gemini 3 Pro' },
      { value: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro' },
      { value: 'gemini-2.5-flash', name: 'Gemini 2.5 Flash' },
      { value: 'gemini-1.5-pro', name: 'Gemini 1.5 Pro' },
      { value: 'gemini-1.5-flash', name: 'Gemini 1.5 Flash' },
    ],
    defaultModel: 'gemini-3-pro',
    keyLabel: 'Google API Key',
    keyHint: '请输入 Google AI Studio API Key',
    baseUrlHint: 'API服务器地址',
    icon: 'https://unpkg.com/@lobehub/icons-static-png@latest/light/gemini.png',
  },
  moonshot: {
    name: 'Moonshot AI',
    baseUrl: 'https://api.moonshot.cn/v1',
    endpoint: '/chat/completions',
    models: [
      { value: 'moonshot-v1-8k', name: 'Moonshot V1 8K' },
      { value: 'moonshot-v1-32k', name: 'Moonshot V1 32K' },
      { value: 'moonshot-v1-128k', name: 'Moonshot V1 128K' },
    ],
    defaultModel: 'moonshot-v1-8k',
    keyLabel: 'Moonshot API Key',
    keyHint: '请输入 Kimi 开放平台 API Key',
    baseUrlHint: 'API服务器地址',
    icon: 'https://unpkg.com/@lobehub/icons-static-png@latest/light/moonshot.png',
  },
  glm: {
    name: '智谱GLM',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    endpoint: '/chat/completions',
    models: [
      { value: 'glm-4-flash', name: 'GLM-4-Flash (推荐)' },
      { value: 'glm-4-flashx', name: 'GLM-4-FlashX' },
      { value: 'glm-4-plus', name: 'GLM-4-Plus' },
      { value: 'glm-4-0520', name: 'GLM-4-0520' },
      { value: 'glm-4-long', name: 'GLM-4-Long' },
      { value: 'glm-4v-plus', name: 'GLM-4V-Plus (多模态)' },
    ],
    defaultModel: 'glm-4-flash',
    keyLabel: '智谱 API Key',
    keyHint: '需要填入有效的智谱API密钥方可使用',
    baseUrlHint: '智谱GLM API服务器地址',
    icon: 'https://unpkg.com/@lobehub/icons-static-png@latest/light/zhipu.png',
  },
  deepseek: {
    name: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com',
    endpoint: '/chat/completions',
    models: [
      { value: 'deepseek-chat', name: 'DeepSeek-V3 (Chat)' },
      { value: 'deepseek-reasoner', name: 'DeepSeek-R1 (Reasoner)' },
    ],
    defaultModel: 'deepseek-chat',
    keyLabel: 'DeepSeek API Key',
    keyHint: '需要填入有效的DeepSeek API密钥方可使用，请确保账户余额充足',
    baseUrlHint: 'DeepSeek API服务器地址',
    icon: 'https://unpkg.com/@lobehub/icons-static-png@latest/light/deepseek.png',
  },
  ollama: {
    name: 'Ollama',
    baseUrl: 'http://localhost:11434/v1',
    endpoint: '/chat/completions',
    models: [
      { value: 'llama3.2', name: 'Llama 3.2' },
      { value: 'qwen2.5', name: 'Qwen 2.5' },
      { value: 'gemma2', name: 'Gemma 2' },
      { value: 'mistral', name: 'Mistral' },
    ],
    defaultModel: 'llama3.2',
    keyLabel: 'API Key (可选)',
    keyHint: '本地部署通常不需要 API Key',
    baseUrlHint: 'Ollama 服务地址',
    icon: 'https://unpkg.com/@lobehub/icons-static-png@latest/light/ollama.png',
  },
  lmstudio: {
    name: 'LM Studio',
    baseUrl: 'http://localhost:1234/v1',
    endpoint: '/chat/completions',
    models: [
      { value: 'local-model', name: 'Local Model' },
    ],
    defaultModel: 'local-model',
    keyLabel: 'API Key (可选)',
    keyHint: '本地部署通常不需要 API Key',
    baseUrlHint: 'LM Studio 服务地址',
    icon: 'https://unpkg.com/@lobehub/icons-static-png@latest/light/lmstudio.png',
  },
  comp_share: {
    name: '优云智算',
    baseUrl: 'https://api.compshare.cn/v1',
    endpoint: '/chat/completions',
    models: [
      { value: 'gpt-4o', name: 'GPT-4o' },
      { value: 'claude-3-5-sonnet', name: 'Claude 3.5 Sonnet' },
    ],
    defaultModel: 'gpt-4o',
    keyLabel: 'API Key',
    keyHint: '请输入优云智算 API Key',
    baseUrlHint: 'API服务器地址',
    icon: 'https://unpkg.com/@lobehub/icons-static-png@latest/light/openai.png',
  },
  '302_ai': {
    name: '302.AI',
    baseUrl: 'https://api.302.ai/v1',
    endpoint: '/chat/completions',
    models: [
      { value: 'gpt-4o', name: 'GPT-4o' },
      { value: 'claude-3-5-sonnet-20240620', name: 'Claude 3.5 Sonnet' },
    ],
    defaultModel: 'gpt-4o',
    keyLabel: 'API Key',
    keyHint: '请输入 302.AI API Key',
    baseUrlHint: 'API服务器地址',
    icon: 'https://unpkg.com/@lobehub/icons-static-png@latest/light/ai302.png',
  },
  pony: {
    name: '小马算力',
    baseUrl: 'https://api.tokenpony.cn/v1',
    endpoint: '/chat/completions',
    models: [
      { value: 'gpt-4o', name: 'GPT-4o' },
    ],
    defaultModel: 'gpt-4o',
    keyLabel: 'API Key',
    keyHint: '请输入小马算力 API Key',
    baseUrlHint: 'API服务器地址',
    icon: 'https://unpkg.com/@lobehub/icons-static-png@latest/light/openai.png',
  },
  siliconflow: {
    name: '硅基流动',
    baseUrl: 'https://api.siliconflow.cn/v1',
    endpoint: '/chat/completions',
    models: [
      { value: 'deepseek-ai/DeepSeek-V3', name: 'DeepSeek-V3' },
      { value: 'deepseek-ai/DeepSeek-R1', name: 'DeepSeek-R1' },
      { value: 'Qwen/Qwen2.5-72B-Instruct', name: 'Qwen2.5-72B' },
      { value: 'Qwen/Qwen2.5-7B-Instruct', name: 'Qwen2.5-7B' },
      { value: 'Qwen/QwQ-32B', name: 'QwQ-32B' },
      { value: 'THUDM/glm-4-9b-chat', name: 'GLM-4-9B' },
    ],
    defaultModel: 'deepseek-ai/DeepSeek-V3',
    keyLabel: 'SiliconFlow API Key',
    keyHint: '需要填入有效的硅基流动API密钥方可使用',
    baseUrlHint: '硅基流动 API服务器地址',
    icon: 'https://unpkg.com/@lobehub/icons-static-png@latest/light/openai.png',
  },
  ppio: {
    name: 'PPIO 派欧云',
    baseUrl: 'https://api.ppinfra.com/v3/openai',
    endpoint: '/chat/completions',
    models: [
      { value: 'qwen2.5-72b-instruct', name: 'Qwen2.5-72B' },
    ],
    defaultModel: 'qwen2.5-72b-instruct',
    keyLabel: 'API Key',
    keyHint: '请输入 PPIO API Key',
    baseUrlHint: 'API服务器地址',
    icon: 'https://unpkg.com/@lobehub/icons-static-png@latest/light/ppio.png',
  },
  modelscope: {
    name: 'ModelScope',
    baseUrl: 'https://api-inference.modelscope.cn/v1',
    endpoint: '/chat/completions',
    models: [
      { value: 'qwen/Qwen-7B-Chat', name: 'Qwen-7B' },
    ],
    defaultModel: 'qwen/Qwen-7B-Chat',
    keyLabel: 'API Key',
    keyHint: '请输入 ModelScope API Key',
    baseUrlHint: 'API服务器地址',
    icon: 'https://unpkg.com/@lobehub/icons-static-png@latest/light/modelscope.png',
  },
  oneapi: {
    name: 'OneAPI',
    baseUrl: 'https://api.oneapi.xyz/v1',
    endpoint: '/chat/completions',
    models: [
      { value: 'gpt-3.5-turbo', name: 'GPT-3.5 Turbo' },
    ],
    defaultModel: 'gpt-3.5-turbo',
    keyLabel: 'API Key',
    keyHint: '请输入 OneAPI Key',
    baseUrlHint: 'API服务器地址',
    icon: 'https://unpkg.com/@lobehub/icons-static-png@latest/light/openai.png',
  },
};

export const SUPPORTED_FILE_TYPES = [
  'application/pdf',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-powerpoint',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'text/plain',
] as const;

export const FILE_SIZE_LIMIT = 50 * 1024 * 1024;

export const FUNCTION_INFO = {
  news: {
    icon: '📰',
    name: '要闻概览',
    description: '新闻要点梳理',
  },
  data: {
    icon: '📊',
    name: '罗森析数',
    description: '数据内容分析',
  },
  science: {
    icon: '🔬',
    name: '理工速知',
    description: '理工课件整理',
  },
  liberal: {
    icon: '📚',
    name: '文采丰呈',
    description: '文科课件整理',
  },
} as const;
